// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryevqnnsfzociewzmyud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5ZXZxbm5zZnpvY2lld3pteXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5MjgxOTgsImV4cCI6MjA3MjUwNDE5OH0.EZ5q9lLuIaT2BIWNqz6eV3SWJqTgqfYASwHx65rCN9w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});